import { StyleSheet } from 'react-native';
var React = require('react-native');


module.exports = StyleSheet.create({

  container: {
    flex: 1,
    backgroundColor: 'black',
    flexDirection: 'column',
    //alignItems: 'center',
    justifyContent: 'center',
  },
  apptitle: {
    color: 'crimson',
    fontFamily: 'vincHand',
    fontSize: 64,
    top: '5%',
    left: '68%'
  },
  regular: {
    fontFamily: 'Cochin',
    color: '#cb4154',
    fontSize: 18,
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  contentContainer: {
    flex: .8,
    //paddingTop: 80,
    top: '10%',
    //justifyContent: 'center',
    textAlign: 'center',
    backgroundColor: 'black',
    width: '80%',
    alignSelf: 'center',
  },
  agreeButtons:{
    flex: .4,
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    alignSelf: 'center',
    fontSize: 52,
    fontWeight: 'bold',
    width: '60%',
  },
  SignInButton:{
    backgroundColor: 'red',
    borderColor: 'yellow',
  },
  homeTitle: {
    flex: .2,
    //zIndex: 2,
    //position: 'relative',
    color: 'crimson',
    fontFamily: 'vincHand',
    fontSize: 40,
    top: '9%',
    //left: '60%',
  },
  homeCon: {
    flex: .6,
    backgroundColor: 'black',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'stretch',
    //marginTop: '-25%',
  },
  homeSubTitles: {
    color: 'crimson',
    //fontFamily: 'vincHand',
    fontFamily: 'Cochin',
    fontSize: 30,
    marginLeft: '5%',
    paddingBottom: 5,
    //marginTop: '-20%',
    //marginBottom: '-25%',
  },
  homeTextinput: {
    color: 'pink',
    fontSize: 24,
    fontFamily: 'Cochin',
    height: 60,
    borderColor: '#cb4154',
    borderBottomWidth: 2,
    width: '70%',
    marginLeft: '5%',
    //marginLeft: '5%',
    marginTop: '-20%',
  },
  lcupCont: {
    flex: .1,
    flexDirection: 'row',
    alignSelf: 'center',
  },
  lcupLabel: {
    zIndex: 2,
    fontSize: 20,
    color: 'pink',
    backgroundColor: 'black',
    fontFamily: 'Cochin',
    padding: 2,
    marginBottom: -100,
    alignSelf: 'center',
  },
  lcupbutton: {
    zIndex: 1,
    opacity: .4,
    borderColor: 'pink',
    borderWidth: 3,
    width: '100%',
    height: '80%',
    padding: 100,
    alignSelf: 'center',
  },
  lcupproc: {
    zIndex: 1,
    opacity: .4,
    borderColor: 'grey',
    borderWidth: 1,
    marginTop: -30,
    width: '300%',
    height: '100%',
    padding: 10,
    alignSelf: 'center',
  },
  lcupprocbut: {
    zIndex: 2,
    opacity: 1,
    color: 'green',
    position: 'absolute',
    backgroundColor: 'black',
    marginTop: -150,
  },
});
